# === PROPIEDADES COMUNES ===

spring.application.name=restaurant

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/restaurant
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Log Spring Security internal events
logging.level.org.springframework.security=DEBUG

# Log HTTP filter chain
logging.level.org.springframework.security.web=DEBUG

# Batching
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false


# === PROPIEDADES PROPIAS DE LA APLICACIÓN ===

# Mercado Pago
app.mercadopago.access-token=${MP_TOKEN:APP_USR-905977818621474-061015-59e3edf5b9b9d6e38fad70eb69035f55-2703688565}

# Tokens
app.auth.access-token.secret=${JWT_SECRET:01234567890123456789012345678901}
app.auth.access-token.duration-minutes=99999

# CORS
app.cors-origins=https://restaurant.gpadilla.com,http://localhost:5173,https://reqbin.com/