# === PROPIEDADES COMUNES ===

spring.application.name=restaurant

# Base de datos
spring.datasource.url=jdbc:sqlite:restaurant.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create

# Archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Log Spring Security internal events
logging.level.org.springframework.security=DEBUG

# Log HTTP filter chain
logging.level.org.springframework.security.web=DEBUG

# Batching
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false


# === PROPIEDADES PROPIAS DE LA APLICACIÓN ===

# Mercado Pago
#app.mercadopago.access-token=${MP_TOKEN}

# Tokens
app.auth.access-token.secret=${JWT_SECRET:01234567890123456789012345678901}
app.auth.access-token.duration-minutes=99999

# CORS
app.cors-origins=https://restaurant.gpadilla.com